services:
  postgres:
    image: postgres:16-alpine
    restart: always
    container_name: scvet-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aaabbb
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 6432:5432